on:
  workflow_dispatch:
    inputs:
      TAG:
        description: "A tag to deploy to production"
        type: string
        required: true
  release:
    types: [published]

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.TAG }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: npm test
        if: runner.os == 'Linux'
      - run: npm test
        if: runner.os != 'Linux'
      - name: Publish
        if: success() && matrix.os == 'ubuntu-latest'
        run: npm run deploy -- --noVerify
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}